### ISSUE TITLE
Feature Request: Previous/Next Day in Photo Picker

### ISSUE THREAD

**Issue by leoccyao** [alangrainger/obsidian-google-photos#10]
I really appreciate the well-thought out functionality of limiting photos to a certain day, as it helps greatly with adding photos to older entries. However, with events that run late and delays receiving photos from others, my photos from a certain day sometimes end up with timestamps a day or two after!

Right now, the only way to access those photos is to scroll through my entire library, or to insert them on a different daily note then copy over the embed. Adding previous/next day buttons would help with more easily accessing photos with slightly-off timestamps.

A date picker in the modal might also be nice, to help with finding photos when adding to non-daily notes.

**Comment by alangrainger** [comment]
Added in version 1.2.0

![image](https://user-images.githubusercontent.com/16197738/218043159-e7609cb2-2ecf-4b39-b570-df20978965f3.png)
