### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ricraftis** [alangrainger/obsidian-google-photos#14]
Hi Alan,

I'm just writing an article and doing a video for your plugin. When doing so, I noticed you couldn't select a date range for the photos to look at in Google. I think this would be a really handy feature to add to the plugin. The article will be on my site at ricraftis.au in the coming days btw. 

Cheers, 

Ric

**Comment by ricraftis** [comment]
> 

Here's a link to the article. If you have any suggestions for additions or clarifications, feel free to reach out. Cheers.

**Comment by alangrainger** [comment]
Date range added in 1.3.0, many thanks to @Ebonsignori !
