### ISSUE TITLE
Some gmail accounts don't work

### ISSUE THREAD

**Issue by rveciana** [alangrainger/obsidian-google-photos#15]
I don't know if it's related to the plugin or the API configuration or the accounts, but some gmail accounts work, but others show a white page when logging in, instead of the buttons to give persmission.

Open Photos API auth -> A dialog appears where you put the email -> Blank dialog that doesn't change

Do you know what can that be?

**Comment by dchirst** [comment]
I'm also having this issue!

**Comment by alangrainger** [comment]
Are there any useful looking error messages in the console of the login window?

**Comment by rveciana** [comment]
I don't see anything strange. The auth calls this endpoint: https://ssl.gstatic.com/accounts/static/_/js/k=gaia.gaiafe_signin.ca.2AYFzSMYyV4.O/am=AISXDAAAAAAAAAAAQNQE/d=0/rs=ABkqax13wJkKLOIr7fZrvc685cDBALDIxQ/m=sy2,sy3,sy4,nCyKU

The response is something, but the screen has no content. Response:
this._G=this._G||{};(function(_){var window=this;
try{
var MA,fha,gha,PA,QA;_.KA=function(a){if(0<a.Ya.length)return _.Ro(a.Ya[0])};
_.LA=function(a,b){a.xb(function(c){var d=c.type;switch("string"===typeof d&&d.toLowerCase()){case "checkbox":case "radio":c.checked=b;break;case "select-one":c.selectedIndex=-1;if("string"===typeof b)for(var e=0;d=c.options[e];e++)if(d.value==b){d.selected=!0;break}break;case "select-multiple":d=b;"string"===typeof d&&(d=[d]);for(var f=0;e=c.options[f];f++)if(e.selected=!1,d)for(var g,h=0;g=d[h];h++)e.value==g&&(e.selected=!0);break;default:c.value=null!=b?b:""}})};
MA=function(a){this.l=a;this.i=new _.Rc;this.g=null};MA.prototype.init=function(a){this.g||(this.g=_.ho(new _.ne(this.l.map(function(b){return b(a)})),this.i));return this.g};MA.prototype.done=function(){return this.i};_.NA=function(a){return a.ra.i?a.ra.i:a.ra.i=new _.dd(a)};fha=function(a,b){b&&(a[_.ke]=new MA(b),a[_.ke].done().addCallback(function(){a[_.ke]=null}))};_.OA=function(a,b,c){a=b(c||{},_.Yz(a));return String(a)};gha={Yd:_.Je};PA=function(a,b){a.o||(a.o=[]);a.o.push(b)};
QA=function(a,b,c,d){a=_.Kt.call(this,a,void 0,d)||this;a.l=b;a.i=c;a.da=new _.sw;a.o=null;return a};_.A(QA,_.Kt);_.k=QA.prototype;_.k.ic=function(){return this.i.g};_.k.Cc=function(){return this.i.g||void 0};_.k.getContext=function(a){return _.je(this.l,a)};_.k.ta=function(){return this.da.g?this.da.g:this.da.g=new _.ov(this.l)};_.k.getData=function(a){return this.ta().getData(a)};
_.k.Yd=function(a,b){var c=this;return _.Tf(gha.Yd(b||this.l,a,this.Cc()),function(d){d instanceof _.Ie&&(d.message+=" requested by "+c);return d})};_.k.Hc=function(a,b){if(a.tagName){var c=this.i.Hc(a),d=c.kc();PA(this,function(e){return d.addCallback(function(f){return _.me(f,e)})});b&&c.addCallback(b);return c}return this.Ge(a).addCallback(function(e){if(0==e.length)throw Error("nb`"+a+"`"+this);b&&b(e[0]);return e[0]},this)};
_.k.Ge=function(a,b){var c=[],d=_.tw(this.l,a),e=this.ta().ha();if(0==d.size()&&"loading"==e.ownerDocument.readyState){var f=new _.Rc;_.ml(e.ownerDocument,"readystatechange",function(){_.On(this.Ge(a,b),function(h){f.callback(h)},function(h){f.g(h)})},!1,this);return f}d.xb((0,_.Kc)(function(h){c.push(this.i.Hc(h))},this));d=_.it(c);var g=d.kc();PA(this,function(h){return g.addCallback(function(m){return _.it(m.map(function(n){return _.me(n,h)}))})});b&&d.addCallback(b);return d};
_.RA=function(a,b){_.It(b);b.prototype.Dd||(b.prototype.Dd={});a&&(_.Ce.Oa().register(a,b),b.create=function(c,d,e){var f=new QA(c,d,e,b);return _.Me(c,b,f).addCallback(function(g){fha(g,f.o)})})};
}catch(e){_._DumpException(e)}
try{
_.u("nCyKU");
var cya=_.w("nCyKU");var q9=function(a){_.J.call(this,a.Fa);this.o=this.ia("J2uaq")};_.A(q9,_.J);q9.xa=_.J.xa;q9.prototype.i=function(){return _.KA(this.o).toString()};q9.prototype.l=function(){var a=this.i();a=_.Wp(new _.kf(window.location.href),"hl",a).toString();_.yd(window.location,_.Gd(a))};_.K(q9.prototype,"iktSbe",function(){return this.l});_.K(q9.prototype,"TsEH4c",function(){return this.i});_.RA(cya,q9);
_.v();
}catch(e){_._DumpException(e)}
})(this._G);
// Google Inc.

**Comment by dchirst** [comment]
@rveciana I just retried it and the Google account that wasn't working started working for me! Would you try again? Maybe this was a Google issue.

**Comment by rveciana** [comment]
Yes, it works now, thank you! I didn't do anything, just try to authenticate again.
