### ISSUE TITLE
Feature request: Show photos side-by-side with currently selected daily notes (in a sidebar, perhaps)

### ISSUE THREAD

**Issue by parallelinnovation** [alangrainger/obsidian-google-photos#16]
Instead of the current configuration, where a window appears over top of the current day that you can select pictures to insert, imagine if you could see the photos of a day side-by-side with the notes of that particular day. If you change the daily note you're currently on, the photos in the sidebar will also update. 

The goal is to see your photos and notes for each day together, for those who use Google Photos. I think it would be really useful for going back on days to get an overview of your own history and to spark your memories.

**Comment by alangrainger** [comment]
You can currently do that using the codeblock function, which you can add to your daily template.

Try this (for today's date):

````
```photos
{
  "filters": {
    "dateFilter": {
      "dates": [{
        "year": 2023,
        "month": 6,
        "day": 22
      }]
    }
  }
}
```
````

If you use Templater to insert the current date, you'll have a block of today's photos each day.

**Comment by parallelinnovation** [comment]
Thanks a bunch!
