### ISSUE TITLE
Define the height  and width of the frame

### ISSUE THREAD

**Issue by tecnoborder** [alangrainger/obsidian-google-photos#2]
I love the plugin! It was the missing piece of Obsidian. I was wondering how it is possible to set a custom width/height for the frame (the same way that can be done with a traditional iframe)

**Comment by alangrainger** [comment]
I'm not sure what "frame" you mean - do you mean around and individual photo or the popup frame with all the thumbnails? Or something else?

Either way, you can change anything about this plugin with CSS. Just target one of these using a CSS snippet:

`.google-photos-grid-thumbnail` - the thumbnail images
`.google-photos-codeblock` - the embedded codeblock container
`.google-photos-modal-grid` - the popup modal grid container

The inserted images are normal Markdown images, so target them like you would any image.

**Comment by tecnoborder** [comment]
I meant the container! thank you so much for the prompt reply!
