### ISSUE TITLE
Authorization Error

### ISSUE THREAD

**Issue by EkanshdeepGupta** [alangrainger/obsidian-google-photos#22]
Hi, I added Authorized redirect URIs. I put the following link: `https://alangrainger.github.io/obsidian-google-auth-proxy/?handler=google-photos`

However in Obsidian when I click 'Open Photos API Auth', I get the following Authorization Error.

![Screenshot from 2023-09-17 17-18-16](https://github.com/alangrainger/obsidian-google-photos/assets/13527018/4a72e3d4-7f99-4dc2-89ef-f1e426bcf68a)

I do not fully understand the mechanics of how this works, can you help me figure this out? This might have something to do with the 'OAuth consent screen' step of the setup which is not well-documented in this repo.

**Comment by EkanshdeepGupta** [comment]
No I wasn't, thanks a lot! I just updated the plugin. This issue seems to have gone away, but now I am facing a different error message:

![image](https://github.com/alangrainger/obsidian-google-photos/assets/13527018/9a41499c-ca5e-4794-9129-a7f384201e78)

Do you know what might be happening?

**Comment by EkanshdeepGupta** [comment]
Clicking on `error details` opens a pop-up with the following text:
```
Error 403: access_denied
Request details: access_type=offline response_type=code state=state_parameter_passthrough_value redirect_uri=https://alangrainger.github.io/obsidian-google-auth-proxy/?handler=google-photos include_granted_scopes=true client_id=405324060769-4o6f6m8bboco4bq01rmgskgngaqh8mkg.apps.googleusercontent.com scope=https://www.googleapis.com/auth/photoslibrary.readonly 
```

with a link to the following: [Related Developed Documentation](https://developers.google.com/identity/protocols/oauth2/production-readiness/brand-verification?hl=en#projects-used-in-dev-test-stage)

**Comment by alangrainger** [comment]
Thanks, I've rolled back to the previous authentication method: https://github.com/alangrainger/obsidian-google-photos/releases/tag/1.6.1

You'll need to change the Redirect URI back to `https://localhost/google-photos`

Sorry for the hassle.

**Comment by alangrainger** [comment]
Documentation has now been updated to match the new Google API setup process.

Please update the plugin to 1.6.2 and follow the updated docs here:

https://github.com/alangrainger/obsidian-google-photos/blob/main/docs/Setup.md

**Comment by EkanshdeepGupta** [comment]
GREAT. Now it works beautifully! Thanks a lot  for putting in the effort, much appreciated :)
