### ISSUE TITLE
Setup instructions don't reflect current Google API console UX

### ISSUE THREAD

**Issue by lymeswold** [alangrainger/obsidian-google-photos#23]
I had this plugin working a while back but after not using it recently, it looks like I need to regenerate the client id & client secret. The setup instructions don't seem to reflect the latest Google API user interface. I'm lost.

Specifically, after creating a new project and enabling the Photos Library API for it, it wants me to complete the OAuth consent screen (I think this is the point at which I've gone wrong, but I can't see a sensible alternative). It will only allow User Type 'External'. On pressing CREATE it displays a screen which is obviously intended for the developer rather than a user.

Would be grateful if the setup instructions could be checked and verified against the most recent version of the Google Cloud API Console UX.

**Comment by alangrainger** [comment]
Please update to 1.6.2 and follow the updated docs here:

https://github.com/alangrainger/obsidian-google-photos/blob/main/docs/Setup.md

Let me know if any issues.
