### ISSUE TITLE
Toggle in settings to have the limit photos option on by default not working

### ISSUE THREAD

**Issue by devinat1** [alangrainger/obsidian-google-photos#24]
I do not want all my photos to be shown by default I do the Google Photos: Insert Google Photo command.
This is because I often insert a photo of my notes that I took that day (or in the range of days which I specify via the "Show photos in range of days?" toggle, but its annoying and a privacy issue (others peering at my laptop etc.) for all my photos to show up.
Therefore, it would be nice to allow the option for the limiting of photos shown to be on by default.

**Comment by devinat1** [comment]
I think this might already be an option via "default to limiting shown photos to dates", but I am getting this error message:
![image](https://github.com/alangrainger/obsidian-google-photos/assets/15788108/fcfa0cfc-6bf9-4782-b44a-67d77e0e7570)

**Comment by devinat1** [comment]
Note that this is for Obsidian v1.4.13 (which includes the new properties feature). I previously had YAML which looks like this within each file:
---
tags:
  - idea
date: 2023-09-23
last_attempted: 2023-09-23
rating: 
minutes_taken:
---

**Comment by alangrainger** [comment]
Have you chosen to use "Frontmatter" as the source for your note date, rather than title?
