### ISSUE TITLE
Authorization Error (fixed by restarting obsidian)

### ISSUE THREAD

**Issue by kkartch0** [alangrainger/obsidian-google-photos#25]
I kept running into the error pictured below. But restarting Obsidian after entering the client id and secret fixed it. Posting here in case it would be beneficial to add a note at the end of the setup instructions instructing the user to restart Obsidian. Thanks for the great plugin!

![image](https://github.com/alangrainger/obsidian-google-photos/assets/46807501/5e5b9499-60d9-47e9-9b5d-9bef6be4df56)

**Comment by fbreitwieser** [comment]
got the same experience ! After restart it worked

**Comment by alangrainger** [comment]
Thanks for reporting 👍  Fixed in 1.6.3
