### ISSUE TITLE
Authorization problem

### ISSUE THREAD

**Issue by Knaackee** [alangrainger/obsidian-google-photos#26]
Hey, 

at first, thanks for your great work!

I just installed the plugin and did the Google cloud stuff without a problem.

The problem is that the redirect after auth isn't working.

- The auth popup opens in my chrome browser
- i accept
- Google redirects me to: `http://localhost:51894/google-photos?state=state_parameter_passthrough_value&code=...code...&scope=https://www.googleapis.com/auth/photoslibrary.readonly`
- This results in 

```
This site can’t be reachedlocalhost refused to connect.
Try:

Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
ERR_CONNECTION_REFUSED

```

Any idea?

**Comment by alangrainger** [comment]
What operating system / device are you using?

**Comment by Knaackee** [comment]
I am using Windows 11.

**Comment by alangrainger** [comment]
Can you test it in the Sandbox vault? I have tested just now and I don't receive that error on Windows 11.

If you still receive the error, I suggest it might be some firewall software running on your computer?

**Comment by Knaackee** [comment]
I will try this and report back.

**Comment by Knaackee** [comment]
I tried a new vault, disabling the firewall completly and tried it in chromes incognito mode. 
Still the same.  ERR_CONNECTION_REFUSED

Thanks for your help!
