### ISSUE TITLE
Filtering issue

### ISSUE THREAD

**Issue by Knaackee** [alangrainger/obsidian-google-photos#27]
Again, thanks for your work!

I have some issues. I want to show my images in my daily note. 

Dermine date from: `Notes title`
Title date format: `YYYY-MM-DD-dddd`

E.g. the title note for today is `2023-09-25-Monday`.

## 1. The first thing I tried was using:

```
    ```photos
    today
    ```
```

But this always shows the images from today and not from the date specified in the title. 

## 2. I tried the query

```
  ```photos
  {
    "query": {
      "filters": {
        "dateFilter": {
          "dates": [{
            "year": 2023,
            "month": 9,
            "day": 23
          }]
        },
      }
    }
  }
    ```
```


This shows all the images in google photos, for every day.

Any idea what I am doing wrong? 

Thanks again!

**Comment by alangrainger** [comment]
> But this always shows the images from today

![image](https://github.com/alangrainger/obsidian-google-photos/assets/16197738/1049ecb2-12a8-4a74-8dd2-84163e36cde9)

**Comment by Knaackee** [comment]
The docs are good, it was my mistake. It tried notedate before, but it wasnt working. So i assumed it was a placeholder in the docs and then tried today. 

Now its working, i love it.

Thanks and apologize for wasting your time with this issue.
