### ISSUE TITLE
[FR] Add thumbnail URL to note properties when adding photo

### ISSUE THREAD

**Issue by Kageetai** [alangrainger/obsidian-google-photos#28]
I really love the idea of this plugin and will use it for my journaling. I think it can finally replace some external apps I have been using for this.
One more idea would just be to be able to add the URL of the thumbnail also to the notes properties in a chosen property name. Would that be hard to implement?

**Comment by alangrainger** [comment]
See here: https://github.com/alangrainger/obsidian-google-photos#do-the-images-have-to-be-saved-locally-can-they-be-remote-thumbnails

Those links don't exist.

**Comment by Kageetai** [comment]
Sorry, I think I explained wrongly. I didn't mean the URL, but the Obsidian file path to the local thumbnail, just so it can be used more easily by other dataviews or so.

**Comment by alangrainger** [comment]
Understood. In that case I will need quite a bit more detail about how this would work.

Consider a daily journal entry where I add 10 photos. Which one(s) will go in the frontmatter, and how would they be stored?

**Comment by Kageetai** [comment]
Fair point, I only thought of the case with a single photo. The note properties allow arrays of strings as well, so this should technically be possible to just store all photos added to the note, no? I suppose it would need to be an array with a single item as well, for consistency.

**Comment by Kageetai** [comment]
Okay, true, just wanted to bring up the idea to determine whether it's feasable, thx

**Comment by connradolisboa** [comment]
Where do I look for the templater script? I would love to auto add at least the first image link to the properties. This way I can use projects plugin gallery view in my notes.
