### ISSUE TITLE
New 403 Error

### ISSUE THREAD

**Issue by bhemmelgarn** [alangrainger/obsidian-google-photos#29]
I see that there has previously been a 403 error, I believe I have a new one. I completed the setup according to the instructions with no apparent issue. However, when attempting to run a query, I get "Error: Unknown status 403" (image attached) no matter the substance of the query. I have given several hours wait and re-launched Obsidian with no effect, and I cannot click the login button again. 

![image](https://github.com/alangrainger/obsidian-google-photos/assets/105377782/38ca3353-ab92-492b-aa56-e98f6443fbb4)

**Comment by alangrainger** [comment]
When you say "a query", do you mean a codeblock query, or do you mean when running the command `Insert Google Photo` ?

**Comment by bhemmelgarn** [comment]
Both. The above image is what I get when inserting a code block, the below image is when running the command. 
![image](https://github.com/alangrainger/obsidian-google-photos/assets/105377782/43d30682-6039-4694-b17e-23cc0e096185)

**Comment by alangrainger** [comment]
403 error is unauthenticated error from Photos API. Maybe double-triple-quadruple check your Client ID and Secret, and make sure they're exactly the same as on the Google Console.

Double-check also in Google Console that you have Photos Library API permissions (step 5).

**Comment by bhemmelgarn** [comment]
Same issue. I'll try it again in a sandbox first then try the reinstall.

**Comment by bhemmelgarn** [comment]
That did it. Sorry for the false flag but thank you for the troubleshooting support!
