### ISSUE TITLE
Create a new Google photos album

### ISSUE THREAD

**Issue by kngautham** [alangrainger/obsidian-google-photos#3]
Can I use the following custom codeblocks as mentioned in Google photos API

https://developers.google.com/photos/library/reference/rest/v1/albums/create

I am not a programmer and trying to create the album using your plugin

**Comment by alangrainger** [comment]
My plugin currently only requests read-only access to your photo library for safety. Can you give some more details? What is the use-case? Why would you want to create an album via a codeblock?

**Comment by kngautham** [comment]
I have one Project per page and many sub headings. When I am working on a sub heading, I would like to double click the heading and create a photo album with that name (Also the link back to that album is stored under that heading) so that I can add photos of interesting things pertaining to that specific heading. I am doing this manually right now. Your Plugin is very good and you can consider this as an additional feture if it can be implemented easily. Thank you very much for the plugin

**Comment by alangrainger** [comment]
Sounds interesting, but what's the reason for using Google Photos for this, as it doesn't seem fit for purpose. Imagine that your project also has a PDF file or a spreadsheet or even a plain text file. You've now got some project assets in one place (perhaps Obsidian) and some in a totally different storage location, neither of which can be managed through the same interface. And if you wanted to collate all those assets into a zip file to send them to someone else, it would be much more complicated.

Regardless, it's most definitely not easy to implement, so I suggest Google Photos is possibly not the right tool for this job. Perhaps you want a Digital Asset Management system (DAM) ?

**Comment by kngautham** [comment]
Thanks for insightful reply. I will rearrange my workflow
