### ISSUE TITLE
Can't install version 1.6.4

### ISSUE THREAD

**Issue by Kageetai** [alangrainger/obsidian-google-photos#30]
Not really sure what's happening, but the latest update 1.6.4 can't be installed. See video:

https://github.com/alangrainger/obsidian-google-photos/assets/1738309/fb428777-eeda-4ab1-ae57-d61971ac7363

Already tried to uninstall and reinstall.
Maybe the assets are missing or so?!

**Comment by alangrainger** [comment]
Thanks - not sure what's happened there! I've just published 1.6.5 to see if re-publishing solves anything. Please see if you can install that instead.

**Comment by Kageetai** [comment]
Thanks for the speedy reply. That seems to have worked. Perfect
