### ISSUE TITLE
Hovering images inserts it into the document

### ISSUE THREAD

**Issue by Kageetai** [alangrainger/obsidian-google-photos#31]
Sorry for the spam, but found another issue with the latest release. It now seems like just hovering the image in the selector pop-up, inserts the image into the note.
It otherwise works fine, but is confusing, when it happens without clicking.
I cannot really attach a video this time, as there are some private photos.

**Comment by alangrainger** [comment]
It definitely doesn't for me, and more importantly there were no material in that release - it was just a re-release of the last build.

Please try testing it in a Sandbox vault.

**Comment by Kageetai** [comment]
Okay, I had some more time to investigate and noticed a `mouseover` event listener on the image, and found out it's from the [obsidian image converter plugin](https://github.com/xRyul/obsidian-image-converter). Deactivating this makes it behave normally again. I will open an issue on their side.
