### ISSUE TITLE
[FR] Add photo location (or other EXIF data) to note frontmatter

### ISSUE THREAD

**Issue by Kageetai** [alangrainger/obsidian-google-photos#32]
Hey,
I mostly use this plugin with my journal entries, and was wondering whether it's possible to use a feature I often saw in other journal apps, meaning when adding a photo, it takes the location data (and optionally maybe time) from that photo and adds it to the metadata/frontmatter of that note.
Would that be possible/feasible here as well?

**Comment by alangrainger** [comment]
Interesting idea, how would that work with multiple photos in a journal entry?

**Comment by Kageetai** [comment]
Maybe if there is already location data in the frontmatter present, prompt the user whether to overwrite it? Or a toggle in the settings to always overwrite or noTt!

**Comment by Kageetai** [comment]
Just found [this plugin](https://github.com/jose-elias-alvarez/obsidian-geocoding-properties), that kinda solves a similar use case, but would still be nice to be able to extract it automatically.
And this _Geocoding Properties_ also allows overriding existing properties...

**Comment by alangrainger** [comment]
Hi @Kageetai it turns out that Google does not provide location data from their Photos API, so sadly this can't be done:

https://developers.google.com/photos/library/reference/rest/v1/mediaItems

**Comment by Kageetai** [comment]
Too bad, but thanks for checking and such
