### ISSUE TITLE
Is it possible to link the thumbnail to Google Photos?

### ISSUE THREAD

**Issue by kmaustral** [alangrainger/obsidian-google-photos#39]
Thank you for the plugin. It adds a lot of value to my daily reviews. 

I had assumed that you could click on a thumbnail and open the full photo in Google Photos. 

I am using this markdown
`[![]({{local_thumbnail_link}})]({{google_photo_url})`

Can this work in code blocks? If not, would it be possible to link the displayed images to the date in Google Photos?

**Comment by alangrainger** [comment]
You do click on the thumbnail and it opens the full photo in Google Photos - that's exactly how the plugin currently works.

It's plain Markdown, so it will work like any normal image link works in Obsidian. Therefore it won't work in codeblocks, because codeblocks in Obsidian don't display images.

Can you explain a bit more what is the actual issue, as what you're describing as your desired behaviour is already exactly how it works.

**Comment by kmaustral** [comment]
Thanks for the reply.

I understand now that the link won't work on the code block. But I can't
get it to work on single images with this kind of code:

![](00%20Attachments/2023-03-01_google-photo_134211.jpg)]({{google_photo_url})

Does that look right?

I'm disabling various other image plugins to see if there is any
interference.

Much appreciated,

Kevin

**Comment by alangrainger** [comment]
If that's your exact code then you're missing the second closing brace `}` after the URL. That will be the issue with the code you've written there.

**Comment by alangrainger** [comment]
There are a couple of issues with the Markdown you have in your comment:

1. You're missing the second closing brace `}` after the URL.
2. You're missing the opening `[` which will turn it into a link.

It should be:

```
[![](local_file.jpg)](https://remote_link)
```

**Comment by kmaustral** [comment]
Many thanks for that. I've corrected the code and it works well now. I don't recall seeing it written like that in the Read Me. It may help to include it. 

Your plugin is much appreciated.

**Comment by alangrainger** [comment]
Probably a good idea to add to the readme, but FYI it's the default text in the settings box. Just delete whatever custom value you added and you'll see this:

![image](https://github.com/alangrainger/obsidian-google-photos/assets/16197738/b80e3a8e-0ec0-4ba1-8fac-b6f52eebebbb)
