### ISSUE TITLE
Create a command to re-generate all added pictures

### ISSUE THREAD

**Issue by muchisx** [alangrainger/obsidian-google-photos#44]
I use git for backing up and I don't include the Media folder in my backups, it would be nice if I could run a command that re-generates the images that I already included in my vault, because when I pull my project into a new device i only see this:

![image](https://github.com/alangrainger/obsidian-google-photos/assets/34131801/889fbdfe-97b6-4778-b772-7a8208ddede9)

and I don't know how to programatically re-generate them without having to erase it, find it and generate it again, which wouldnt be ideal

**Comment by alangrainger** [comment]
Sorry, that is out of scope for the plugin. I strongly suggest that the correct solution for the issue is to sync or copy that folder.

**Comment by muchisx** [comment]
@alangrainger 

While out of scope this might be easily done! Is just finding the image links in all notes (regex or tagging them with a specific id) then looping  through what the plugging already did and regenerating the thumbnails. What do you think?
