### ISSUE TITLE
Display all photos from a specific album

### ISSUE THREAD

**Issue by kngautham** [alangrainger/obsidian-google-photos#5]
I used the following code for displaying photos from an album called Cool.

I used the code from the Google Developers page
https://developers.google.com/photos/library/reference/rest/v1/mediaItems/search

Error I get is Malformed input. Please check the filters you are using.

```photos
{
  "albumId": "Cool"
}
```
Can you tell me the right format to display photos from specific albums. Thanks

**Comment by alangrainger** [comment]
The album ID is a random internal ID assigned by Google, so you can't do it as you have it there. But it's an interesting idea that I could implement to be able to show albums. What would be the benefit of having them inside Obsidian vs viewing them normally in Google Photos?

**Comment by kngautham** [comment]
Your implementation will allow me to view the images in one place and if I need to view the high resolution image for further reading, I can go to the main album. Your implementation will make it easy for quick viewing.

**Comment by alangrainger** [comment]
But you can already view all your Google Photos in one place - in Google Photos. What would be the benefit of having them inside Obsidian vs viewing them normally in Google Photos?

**Comment by tecnoborder** [comment]
+1 to add the option to see albums sn Obsidian. 
Use case (illustrative):
I have in obsidian a note called "Home" structured into different markdown sections (##)  and a series of Albums on Google photos per each home I lived in. I want to access these albums on the "Home" page. The same for Vacations structures into cities that I visited along with contextual information per each travel.

**Comment by tecnoborder** [comment]
The great thing about having albums in Obsidian is the integrated experience I can have between different types of media

**Comment by alangrainger** [comment]
Makes sense, I'll add that in a future release.

**Comment by alangrainger** [comment]
This is now available in v1.4.0 - please update and check it out.

**NOTE:** 

- It shows only your most recently used albums. This should be enough to get started, and I hope to update it in the future so it can fetch more of that list. I'm not yet sure how to do that.
- Clicking on the photos doesn't do anything. I'd be interested to hear feedback on what it _should_ do, in an ideal world.

**Comment by gecicidegisken** [comment]
Hi, this is an old conversation and I'm not sure if it's still relevant but album feature is great for my use case. I've been looking for this kind of integration so thanks! It would be great if we can see a bigger version of the photos (if possible) or go to the album link when clicked on the photos.
