### ISSUE TITLE
Feature Request: Show photo caption

### ISSUE THREAD

**Issue by Sorrieah** [alangrainger/obsidian-google-photos#50]
I'm planning to use this plugin to add photos to my daily journal. My previous method was to just add the photos to my vault, but it's taking up too much space. I always add a caption to the photos, and if I can do that in Google Photos instead of in Obsidian, it would give me a much cleaner note and allow those captions to be used for other albums and purposes, without needing to add them twice.

**Comment by alangrainger** [comment]
Thanks for the suggestion - you can now do this in v1.6.6.

Use the variables in the Inserted Markdown setting to add the caption where you want it in your inserted markdown. For example:

```markdown
[![{{google_photo_desc}}]({{local_thumbnail_link}})]({{google_photo_url}}) 
```

**Comment by Sorrieah** [comment]
Perfect, thank you so much!
