### ISSUE TITLE
Size of photos when selecting on mobile

### ISSUE THREAD

**Issue by itf** [alangrainger/obsidian-google-photos#54]
After an update (I've just updated the app after over a year), now the size of the images when choosing the image on mobile is ridiculously large. It's not a good experience when browsing the photos as we have to scroll a full screen just to go to the next photo,  as well as having to scroll to the sides to see the rest of a photo

**Comment by itf** [comment]
The issue is caused by the change in this line on update 1.67: https://github.com/alangrainger/obsidian-google-photos/blob/b4450867943039dd9672bfa50bd6da77bea7a185/src/renderer.ts#L61

It should be reverted to: img.src = baseUrl + '=w500-h130'  or equivalent. I think this change might have been accidentally commited when testing the pull request https://github.com/alangrainger/obsidian-google-photos/pull/45 , because the discussion says that the change will not be accepted specifically because of this issue

**Comment by alangrainger** [comment]
Thanks for the investigation @itf - I have reverted that change and published in 1.6.8.
