### ISSUE TITLE
Suggestion: save photo ID

### ISSUE THREAD

**Issue by leoccyao** [alangrainger/obsidian-google-photos#9]
I installed this plugin expecting some kind of `MarkdownPostProcessor` based implementation for displaying photos, and was both gladly surprised and impressed by the simple embed-based format. Though linking to the original photo on Google Photos through the `productUrl` provides a persistent user-accessible connection to the original photo, there is currently no way to programmatically get the original photo again, as the `id` is not saved.

This feature request suggests also saving the `id` of the photo somewhere in the embed syntax. This would enable:
- Regenerating thumbnail images by getting a new `baseUrl`, for example if a higher resolution is requested or the image changes
  - This could also work towards implementing #6 , by exposing a command to embed a new `baseUrl` or by adding an event listener that regenerates expired `baseUrl`s on note open
- Building other custom integrations, such as a publishing integration that uses full-resolution versions of photos in the note.

Just saving the photo ID inline is a reasonably simple change, but the embed format can be up to discussion.

The current embed format: `[![](link to thumbnail)](productUrl)`
Possibilities:
- Use the (currently empty) alt text field
- Add a new inline comment containing the ID
- In either of those locations, creating a more nuanced structure to hold arbitrary metadata (such as a greater portion of the `mediaItem` response as JSON)

I personally do not have a preference, as long as the image preview does not become significantly cluttered.

**Comment by alangrainger** [comment]
This will be added as part of request #7 - being able to customise the inserted Markdown.

**Comment by alangrainger** [comment]
`baseUrl` and `id` are now available as variables to use in your own customised Markdown, in v1.1.3.

https://github.com/alangrainger/obsidian-google-photos/releases/tag/1.1.13

For anything additional not covered in this release (e.g. regenerating thumbnails), please submit a pull request.
